services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: unless-stopped
    ports:
      - 1433:1433
    volumes:
      - dbdata:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "kokos_123"

volumes:
  dbdata:

